--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Abdulhadi5692HDI/SpamOnChat
build-by-default: true
branches:
- master
projects:
  SpamOnChat:
    path: "."
    icon: "icon.png"
...
